# Generated by Django 4.1.3 on 2022-11-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_club_field_club_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='festival',
            field=models.CharField(default='', max_length=200),
        ),
    ]
