# Generated by Django 4.1.3 on 2022-12-04 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_club_festival'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='field',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='type',
            new_name='club_type',
        ),
        migrations.RemoveField(
            model_name='club',
            name='festival',
        ),
        migrations.AddField(
            model_name='club',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='num_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manual',
            name='information',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notice',
            name='information',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('information', models.TextField()),
                ('due_date', models.DateField()),
                ('money', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='homepage.club')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('information', models.TextField()),
                ('start_day', models.DateField()),
                ('finish_day', models.DateField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='homepage.club')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('information', models.TextField()),
                ('update_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='homepage.club')),
            ],
        ),
    ]
